### ISSUE TITLE
Wheres dist folder in repo?

### ISSUE THREAD

**Issue by fabricionaweb** [raphaelpor/fitch.js#11]
I would like to add to [jsDelivr](http://ww.jsdelivr.com). 
In **package.json** `main` points to `/dist/index.js`, but `dist` folder is ignored by git

**Comment by raphaelpor** [comment]
@fabricionaweb Thanks for this question!
By default, this is ignored because you can get the dist files by installing Fitch by NPM or linking direct to [https://unpkg.com/fitch/dist/index.umd.min.js](https://unpkg.com/fitch/dist/index.umd.min.js). :wink:
